# Generated by Django 5.2.7 on 2025-10-15 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='XenDev',
            new_name='Clients',
        ),
    ]
